version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  ignore:
    # ignore Maven APIs/SPIs
    - dependency-name: org.apache.maven:*
  groups:
    production-dependencies:
      dependency-type: "production"
    development-dependencies:
      dependency-type: "development"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"